/**
 * Created by Son Pham on 6/3/2016.
 * This include all necessary constants
 */
BASE_HEIGHT = 38.0; //36
MIN_HEIGHT = 33.0; //33
HEIGHT_RANGE = BASE_HEIGHT - MIN_HEIGHT;
RESOLUTION = 5;
HEX_SIZE = 1;
TILE_SELECTION_OFFSET = 5;

// MARS_CONSTANTS
TINT_COLOR = new THREE.Color(0xE18A55);
MARS_COLOR = new THREE.Color(0xC66143);
SKY_COLOR = new THREE.Color(0xFAF4EC);
EXPERIENTIAL_SCALE = 3;

// GAME_CONSTANTS
BASE_MEAN_TEMPERATURE = 218; // Kelvin

// SUN_CONSTANTS
SUN_CYCLE = 4000;
SUN_RADIUS = 15000;
SUN_SIZE = 500;
LIGHT_RADIUS = 1500;
CINE_RADIUS = 500;

// BASE
BASE_RISE = 0.6;
BASE_COEFFICIENT = 50;
BASE_TINT_COEFFICIENT = 10;

// FALL_OUT
MAX_FALLOUT = 10;
FAlLOUT_HALF_LIFE = 70;
FALL_OUT_COLOR = new THREE.Color(0xFF3E1D);
FALL_OUT_COEFFICIENT = 80;

// WATER CONSTANT
WATER_COLOR = new THREE.Color(0x1C5FCC);
WATER_BASE = 34;
WATER_RANGE = WATER_BASE - MIN_HEIGHT;
WATER_COEFFICIENT = 800;
WATER_RISE = 0.1;

// ICE CONSTANT
ICE_BASE = 35.5
ICE_COEFFICIENT = 400;
ICE_RISE = 1.5;
ICE_COLOR = new THREE.Color(0xF9FFFD);

// TREE CONSTANT
TREE_BASE = 35;
TREE_BASE_SCALE = 1/12;
TREE_HEIGHT_SCALE_RANGE = 1/40;
TREE_WIDTH_SCALE_RANGE = 1/20;
LEAF_COLOR = new THREE.Color(0xA9C42A);

// GRASS CONSTANT
GRASS_COLOR = new THREE.Color(0xA9C42A);
GRASS_COEFFICIENT = 50;
GRASS_RISE = .8;

// SAND
SAND_COLOR = new THREE.Color(0xFFDA7F);
SAND_RANGE = 0.4;
SAND_COEFFICIENT = 400;
CLOSE_SAND_COEFFICIENT = 400;

/////////////////////
// EFFECT CONSTANTS
/////////////////////

// EXPLOSION CONSTANT
EXPL_TIME = 30;
EXPL_SMALL_SIZE = 1.0;
EXPL_BIG_SIZE = 3.0;
EXPL_WAVE_TIME = 40;