/**
 * Created by Son Pham on 6/3/2016.
 * This include all necessary constants
 */
BASE_HEIGHT = 36; //36
MIN_HEIGHT = 33; //33
HEIGHT_RANGE = BASE_HEIGHT - MIN_HEIGHT;
RESOLUTION = 15;
HEX_SIZE = 1;

// Game constants
BASE_MEAN_TEMPERATURE = 218; // Kelvin

// Base color
BASE_COEFFICIENT = 50;

// Fallout Constants
MAX_FALLOUT = 10;
FAlLOUT_HALF_LIFE = 70;
FALL_OUT_COLOR = new THREE.Color(0xFF3E1D);
FALL_OUT_COEFFICIENT = 80;

// WATER CONSTANT
WATER_COLOR = new THREE.Color(0x1C5FCC);
WATER_BASE = 33.9;
WATER_RANGE = 33.5 - 33;
WATER_COEFFICIENT = 200;

// TREE CONSTANT
TREE_BASE = 34.10;

// TREE CONSTANT
TREE_BASE_SCALE = 1.4/10;
TREE_HEIGHT_SCALE_RANGE = 1.5/10;
TREE_WIDTH_SCALE_RANGE = 0.5/10;
LEAF_COLOR = 0x37A64E;